version: '3.4'

services:
  s_rabbitmq:
       container_name: c_rabbitmq
       image: rabbitmq:3-management
     
  s_consul:
      container_name: c_consul
      image: consul

  s_sqlserver:
    container_name: c_sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    
  contactservice.api:
    container_name: c_contactservice
    image: ${DOCKER_REGISTRY-}contactserviceapi
    build:
      context: .
      dockerfile: Src/Services/ContactService/ContactService.Api/Dockerfile

  reportservice.api:
    container_name: c_reportservice
    image: ${DOCKER_REGISTRY-}reportserviceapi
    build:
      context: .
      dockerfile: Src/Services/ReportService/ReportService.Api/Dockerfile

  web.apigateway:
    container_name: c_apigateway
    image: ${DOCKER_REGISTRY-}webapigateway
    build:
      context: .
      dockerfile: Src/ApiGateways/Web.ApiGateway/Dockerfile


   